/*
 * Copyright (C) 2012, 2013 Karol Babioch <karol@babioch.de>
 * Copyright (c) 2010 Frank Meyer - frank(at)fli4l.de
 * Copyright (c) 2010 Vlad Tepesch
 *
 * This file is part of Wordclock.
 *
 * Wordclock is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Wordclock is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wordclock. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file pwm.h
 * @brief Header for manipulating the PWM signal in control of the colors (RGB)
 *
 * The color and brightness of the LEDs on the front panel (and/or the optional
 * Ambilight) is controlled using a [PWM][1] signal for each channel (red,
 * green, blue) separately.
 *
 * This header can be used to manipulate the color itself and/or the
 * brightness.
 *
 * [1]: https://en.wikipedia.org/wiki/Pulse-width_modulation
 *
 * @see pwm.c
 */

#ifndef _WC_PWM_H_
#define _WC_PWM_H_

/**
 * @brief Number of PWM steps
 *
 * The PWM is actually generated by a table containing predefined values. This
 * macro defines the size of the table. Currently there are two such tables,
 * one for 32 steps and another for 64 steps.
 *
 * Obviously by increasing the size of this table the colors can be controlled
 * with more granularity. However this table is stored in program space, which
 * is limited.
 */
#define MAX_PWM_STEPS 32

/**
 * @brief Size of lookup table between the brightness and the PWM signal
 *
 * This defines the size of the table mapping the various brightness values to
 * an index in control of the PWM signal.
 *
 * By increasing the size of this table the brightness can be controlled with
 * more granularity in respect to the measured LDR values (which represent the
 * ambient light conditions). However this table is stored in program space,
 * which is limited.
 */
#define LDR2PWM_COUNT 32

/**
 * @brief Data type for various user defined values
 *
 * This defines the data type for various variables containing user defined
 * values throughout this module regarding the mapping between the measured
 * LDR values and the PWM signal.
 */
#define LDR2PWM_OCC_TYPE uint32_t

/**
 * @brief Data of the PWM module that should be stored persistently in EEPROM
 *
 * The data from this module to be stored persistently in the EEPROM is
 * expected to be in the form of this type.
 *
 * The default values are defined in PWMEEPROMPARAMS_DEFAULT.
 *
 * @see PWMEEPROMPARAMS_DEFAULT
 * @see WcEepromData::pwmParams
 */
typedef struct PwmEepromParams {

    /**
     * @brief The user defined offset to the brightness control
     */
    int8_t brightnessOffset;

    /**
     * @brief Mapping of measured brightness to PWM steps
     */
    uint8_t brightness2pwmStep[LDR2PWM_COUNT];

    /**
     * @brief Bitfield containing array members defined by the user
     */
    LDR2PWM_OCC_TYPE occupancy;

} PwmEepromParams;

/**
 * @brief Default values of this module that should be stored persistently
 *
 * This defines the default values for this module. Refer to PwmEepromParams
 * for a detailed description of each member.
 *
 * @note This will also be the values used after flashing the firmware to the
 * microcontroller, so make sure that the defaults are actually useful.
 *
 * @see PwmEepromParams
 * @see wceeprom.h
 */
#define PWMEEPROMPARAMS_DEFAULT { \
    0, \
    {5, 6, 7, 8, 8, 9, 10, 11, 12, 13, 13, 14, 15, 16, 17, 18, \
    18, 19, 20, 21, 22, 23, 23, 24, 25, 26, 27, 28, 28, 29, 30, 31}, \
    ((LDR2PWM_OCC_TYPE)1) | (((LDR2PWM_OCC_TYPE)1) << (LDR2PWM_COUNT - 1)) \
}

extern void pwm_init();

extern void pwm_on();

extern void pwm_off();

extern void pwm_on_off();

#if (ENABLE_RGB_SUPPORT == 1)

    extern void pwm_set_colors(uint8_t red, uint8_t green, uint8_t blue);

    extern void pwm_get_colors(uint8_t* red, uint8_t* green, uint8_t* blue);

    extern void pwm_set_color_step(uint8_t red, uint8_t green, uint8_t blue);

    extern void pwm_get_color_step(uint8_t* red, uint8_t* green, uint8_t* blue);

#endif

extern void pwm_set_base_brightness_step(uint8_t pwm_idx);

extern void pwm_step_up_brightness();

extern void pwm_step_down_brightness();

extern void pwm_lock_brightness_val(uint8_t val);

extern void pwm_release_brightness();

extern void pwm_modifyLdrBrightness2pwmStep();

#endif /* _WC_PWM_H_ */
