/*
 * Copyright (C) 2013, 2014 Karol Babioch <karol@babioch.de>
 *
 * This file is part of Wordclock.
 *
 * Wordclock is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Wordclock is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wordclock. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file uart_protocol.h
 * @brief Header file of a module
 *
 * This module provides means to handle the UART protocol, which makes it
 * possible to control the Wordclock via a serial connection. The protocol
 * itself is specified within `/doc/UART_PROTOCOL.md`.
 *
 * @see uart_protocol.c
 */

#ifndef WC_UART_PROTOCOL_H
#define WC_UART_PROTOCOL_H

/**
 * @brief Prefix for any output generated by this module
 *
 * @note Only output that is preceded by this prefix is the result of any
 * requests made to this module.
 *
 * @see UART_PROTOCOL_OUTPUT
 */
#define UART_PROTOCOL_OUTPUT_PREFIX ">"

/**
 * @brief EOL marker for any output generated by this module
 *
 * To make it compatible with most of the platforms out there, this is defined
 * as `\r\n`.
 *
 * @see UART_PROTOCOL_OUTPUT
 */
#define UART_PROTOCOL_OUTPUT_EOL "\r\n"

/**
 * @brief EOL marker for any input processed by this module
 *
 * Once this character has been detected, the command will be parsed and
 * executed
 *
 * @note Keep in mind that this needs to be a single character, so enclose it
 * by single quotes.
 */
#define UART_PROTOCOL_INPUT_EOL '\r'

extern void uart_protocol_handle();

#endif /* WC_UART_PROTOCOL_H */
